package org.scam.cadastros;

public enum Curso {

    ADMINISTRADOR, AGRONOMIA,
    ANÁLISE_E_DESENVOLVIMENTO_DE_SISTEMAS,
    ARQUITETURA_E_URBANISMO,
    BIOMEDICINA,
    CIÊNCIAS_BIOLÓGICAS,
    CIÊNCIAS_CONTÁBEIS,
    DESIGN_GRÁFICA_DIGITAL,
    DIREITO,
    EDUCAÇÃO_FÍSICA,
    ENFERMAGEM,
    ENGENHARIA_CIVIL,
    ENGENHARIA_DE_SOFTWARE,
    ENGENHARIA_ELÉTRICA,
    ENGENHARIA_MECÂNICA,
    FARMÁCIA,
    FISIOTERAPIA,
    MEDICINA_VETERINÁRIA,
    NUTRIÇÃO,
    PEDAGOGIA,
    PSICOLOGIA,
    PUBLICIDADE_E_PROPAGANDA

}
